services:
  user.service:
    image: user.service
    build:
      context: .
      dockerfile: src/Presentation/Identity/User.Service/Dockerfile

  plan.service:
    image: plan.service
    build:
      context: .
      dockerfile: src/Presentation/Identity/Plan.Service/Dockerfile

  identity.api:
    image: identity.api
    build:
      context: .
      dockerfile: src/Presentation/Identity/Identity.API/Dockerfile
