services:
  fridge.api:
    image: fridge.api
    environment:
      - ASPNETCORE_HTTP_PORTS=8081
      - ConnectionStrings_Database= $DATABASE_CONNECTION_STRING
    ports:
      - $FRIDGE_API_EXTERNAL_PORT:8081
    build:
      context: .
      dockerfile: src/Presentation/Fridge.API/Dockerfile
    networks:
      default:

  statistic.api:
    image: statistic.api
    environment:
      - ASPNETCORE_HTTP_PORTS=8082
      - ConnectionStrings_Database= $DATABASE_CONNECTION_STRING
    ports:
      - $STATISTIC_API_EXTERNAL_PORT:8082
    build:
      context: .
      dockerfile: src/Presentation/Statistic.API/Dockerfile
    networks:
      default:
      
  user.service:
    image: user.service
    environment:
      - ASPNETCORE_HTTP_PORTS=8083
      - ConnectionStrings_Database= $DATABASE_CONNECTION_STRING
    ports:
      - $USER_API_EXTERNAL_PORT:8083
    build:
      context: .
      dockerfile: src/Presentation/Identity/User.Service/Dockerfile
    networks:
      default:

  plan.service:
    image: plan.service
    environment:
      - ASPNETCORE_HTTP_PORTS=8084
      - ConnectionStrings_Database= $DATABASE_CONNECTION_STRING
    ports:
      - $PLAN_API_EXTERNAL_PORT:8084
    build:
      context: .
      dockerfile: src/Presentation/Identity/Plan.Service/Dockerfile
    networks:
      default:

  identity.api:
    image: identity.api
    environment:
      - ASPNETCORE_HTTP_PORTS=8085
      - ConnectionStrings_Database= $DATABASE_CONNECTION_STRING
      - ConnectionStrings_UserService = $CONNECTION_STRINGS_USER-SERVICE
    ports:
      - $IDENTITY_API_EXTERNAL_PORT:8085
    build:
      context: .
      dockerfile: src/Presentation/Identity/Identity.API/Dockerfile
    networks:
      default:

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    ports:
      - 5011:5432
    networks:
      default:
  
  service-bus:
    image: rabbitmq:3-management-alpine
    ports:
      - 5004:5672
      - 5005:15672
    volumes:
      - ./volumes/ServiceBus/data/:/var/lib/rabbitmq/
      - ./volumes/ServiceBus/log/:/var/log/rabbitmq
    
    networks:
      default:
        
networks:
  default:
    driver: "bridge"