services:
  fridge.api:
    image: fridge.api
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - $FRIDGE_API_EXTERNAL_PORT:8080
    build:
      context: .
      dockerfile: src/Presentation/Fridge.API/Dockerfile
    networks:
      default:

  statistic.api:
    image: statistic.api
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - $STATISTIC_API_EXTERNAL_PORT:8080
    build:
      context: .
      dockerfile: src/Presentation/Statistic.API/Dockerfile
    networks:
      default:
      
  user.service:
    image: user.service
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - $USER_API_EXTERNAL_PORT:8080  
    build:
      context: .
      dockerfile: src/Presentation/Identity/User.Service/Dockerfile
    networks:
      default:

  plan.service:
    image: plan.service
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - $PLAN_API_EXTERNAL_PORT:8080  
    build:
      context: .
      dockerfile: src/Presentation/Identity/Plan.Service/Dockerfile
    networks:
      default:

  identity.api:
    image: identity.api
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - $IDENTITY_API_EXTERNAL_PORT:8080  
    build:
      context: .
      dockerfile: src/Presentation/Identity/Identity.API/Dockerfile
    networks:
      default:

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    
    volumes:
      - ./Volumes/database:/var/lib/postgresql/data
    ports:
      - 5011:5432
    networks:
      default:
        
networks:
  default:
    driver: "bridge"