services:
  fridge.api:
    image: fridge.api
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - 8081:8080
    build:
      context: .
      dockerfile: src/Presentation/Fridge.API/Dockerfile
