# This is a generated file. Not intended for manual editing.
services:
  fridge.api:
    build:
      context: "/home/ianerglitch/Documents/myGeladeiraRemix/MyGeladeiraRemixBackend"
      dockerfile: "src/Presentation/Fridge.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "fridge.api:dev"
    ports:
    - "127.0.0.1:57000:57000"
    - "127.0.0.1:57200:57200"
    - "127.0.0.1:57400:57400"
    volumes:
    - "/home/ianerglitch/Documents/myGeladeiraRemix/MyGeladeiraRemixBackend/src/Presentation/Fridge.API:/app:rw"
    - "/home/ianerglitch/Documents/myGeladeiraRemix/MyGeladeiraRemixBackend:/src:rw"
    - "/home/ianerglitch/.nuget/packages:/home/app/.nuget/packages"
    - "/home/ianerglitch/.local/share/JetBrains/RiderRemoteDebugger/2024.3.3/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/snap/rider/523/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/ianerglitch/.cache/JetBrains/Rider2024.3/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_1_05_08_28_35:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
